### ISSUE TITLE
Would you mind showing a example to use class VersionedFastAPI?

### ISSUE THREAD

**Issue by sevenjay** [Rickaym/Rickaym#1]
Hey there! I really appreciate you refactoring the fastapi-versioning library. I love your changes! Would you mind showing me an example of how to use the VersionedFastAPI class?

**Comment by Rickaym** [comment]
Hey @sevenjay

Thanks for the compliments.
I refactored the library for [freebooksapi](https://github.com/Rickaym/FreeBooksAPI). You can view its usage in the [main.py file](https://github.com/Rickaym/FreeBooksAPI/blob/master/freebooksapi/main.py).

Ricky.

**Comment by sevenjay** [comment]
thanks
